# GitHub Pages Gemfile
source "https://rubygems.org"

# GitHub Pages gem (contains Jekyll and plugins)
gem "github-pages", group: :jekyll_plugins

# Additional gems for development
group :development do
  gem "jekyll", "~> 3.9.0"
  gem "jekyll-feed", "~> 0.15"
  gem "jekyll-sitemap", "~> 1.4"
  gem "jekyll-seo-tag", "~> 2.7"
  gem "jekyll-relative-links", "~> 0.6"
end

# Windows and JRuby support
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]